print("Hello World")
print("Mudassar")
print("This is My First Python Program")
print("I Want To Developer Python")
print("The White Man tigers")
print("uaf")
print("Python Ka ushal")
print("The World Surrounds Around Earth")
print ("Python is a programming language")
print("Ammar")